#
# SPDX-FileCopyrightText: The Wildroid Project
# SPDX-License-Identifier: Apache-2.0
#

WILDROID_MULTIPRODUCT_AOSP_PRODUCTMK := device/pc/basic_x86_64_pc/aosp_basic_x86_64_pc.mk
WILDROID_MULTIPRODUCT_IS_GO := false
WILDROID_MULTIPRODUCT_IS_WIFIONLY := true
WILDROID_MULTIPRODUCT_NAME := basic_x86_64_pc
WILDROID_MULTIPRODUCT_SIZE := full
WILDROID_MULTIPRODUCT_SKIP_DISTROS := lineage
WILDROID_MULTIPRODUCT_TYPE := pc
include vendor/wildroid/multiproduct/AndroidProductsHelper.mk

WILDROID_MULTIPRODUCT_AOSP_PRODUCTMK := device/virt/vboxware/aosp_vboxware.mk
WILDROID_MULTIPRODUCT_IS_GO := false
WILDROID_MULTIPRODUCT_IS_WIFIONLY := true
WILDROID_MULTIPRODUCT_NAME := vboxware
WILDROID_MULTIPRODUCT_SIZE := full
WILDROID_MULTIPRODUCT_SKIP_DISTROS := lineage
WILDROID_MULTIPRODUCT_TYPE := pc
include vendor/wildroid/multiproduct/AndroidProductsHelper.mk

WILDROID_MULTIPRODUCT_AOSP_PRODUCTMK := device/virt/virtio_arm64/aosp_virtio_arm64.mk
WILDROID_MULTIPRODUCT_IS_GO := false
WILDROID_MULTIPRODUCT_IS_WIFIONLY := true
WILDROID_MULTIPRODUCT_NAME := virtio_arm64
WILDROID_MULTIPRODUCT_SIZE := full
WILDROID_MULTIPRODUCT_SKIP_DISTROS := lineage
WILDROID_MULTIPRODUCT_TYPE := pc
include vendor/wildroid/multiproduct/AndroidProductsHelper.mk

WILDROID_MULTIPRODUCT_AOSP_PRODUCTMK := device/virt/virtio_arm64/aosp_virtio_arm64only.mk
WILDROID_MULTIPRODUCT_IS_GO := false
WILDROID_MULTIPRODUCT_IS_WIFIONLY := true
WILDROID_MULTIPRODUCT_NAME := virtio_arm64only
WILDROID_MULTIPRODUCT_SIZE := full
WILDROID_MULTIPRODUCT_SKIP_DISTROS := lineage
WILDROID_MULTIPRODUCT_TYPE := pc
include vendor/wildroid/multiproduct/AndroidProductsHelper.mk

WILDROID_MULTIPRODUCT_AOSP_PRODUCTMK := device/virt/virtio_arm64/aosp_virtio_arm64only_16k.mk
WILDROID_MULTIPRODUCT_IS_GO := false
WILDROID_MULTIPRODUCT_IS_WIFIONLY := true
WILDROID_MULTIPRODUCT_NAME := virtio_arm64only_16k
WILDROID_MULTIPRODUCT_SIZE := full
WILDROID_MULTIPRODUCT_SKIP_DISTROS := lineage
WILDROID_MULTIPRODUCT_TYPE := pc
include vendor/wildroid/multiproduct/AndroidProductsHelper.mk

WILDROID_MULTIPRODUCT_AOSP_PRODUCTMK := device/virt/virtio_arm64/aosp_virtio_arm64only_go.mk
WILDROID_MULTIPRODUCT_IS_GO := true
WILDROID_MULTIPRODUCT_IS_WIFIONLY := true
WILDROID_MULTIPRODUCT_NAME := virtio_arm64only_go
WILDROID_MULTIPRODUCT_SIZE := full
WILDROID_MULTIPRODUCT_SKIP_DISTROS := lineage
WILDROID_MULTIPRODUCT_TYPE := pc
include vendor/wildroid/multiproduct/AndroidProductsHelper.mk

WILDROID_MULTIPRODUCT_AOSP_PRODUCTMK := device/virt/virtio_x86_64/aosp_virtio_x86_64.mk
WILDROID_MULTIPRODUCT_IS_GO := false
WILDROID_MULTIPRODUCT_IS_WIFIONLY := true
WILDROID_MULTIPRODUCT_NAME := virtio_x86_64
WILDROID_MULTIPRODUCT_SIZE := full
WILDROID_MULTIPRODUCT_SKIP_DISTROS := lineage
WILDROID_MULTIPRODUCT_TYPE := pc
include vendor/wildroid/multiproduct/AndroidProductsHelper.mk

WILDROID_MULTIPRODUCT_AOSP_PRODUCTMK := device/virt/virtio_x86_64/aosp_virtio_x86_64_go.mk
WILDROID_MULTIPRODUCT_IS_GO := true
WILDROID_MULTIPRODUCT_IS_WIFIONLY := true
WILDROID_MULTIPRODUCT_NAME := virtio_x86_64_go
WILDROID_MULTIPRODUCT_SIZE := full
WILDROID_MULTIPRODUCT_SKIP_DISTROS := lineage
WILDROID_MULTIPRODUCT_TYPE := pc
include vendor/wildroid/multiproduct/AndroidProductsHelper.mk
