#
# SPDX-FileCopyrightText: The Wildroid Project
# SPDX-License-Identifier: Apache-2.0
#

ifneq ($(filter vboxware virtio_%,$(PRODUCT_DEVICE)),)

ifneq ($(filter miku_%,$(PRODUCT_NAME)),)
BOOTMGR_ANDROID_DISTRIBUTION_NAME := MikuUI $(PLATFORM_MIKU_RELEASE) $(TARGET_MIKU_BUILD_VARIANT) by $(MIKU_MASTER)
BOOTMGR_ANDROID_OTA_PACKAGE_NAME := $(PROD_VERSION).zip
BOOTMGR_ARTIFACT_FILENAME_PREFIX := $(PROD_VERSION)-by-$(MIKU_MASTER)
UTM_VM_NAME := MikuUI
UTM_VM_NOTES_INITIAL_VERSION := $(PROD_VERSION) by $(MIKU_MASTER)
UTM_VM_ZIP_FILENAME_BUILD_DESC := $(BOOTMGR_ARTIFACT_FILENAME_PREFIX)
endif # PRODUCT_NAME

endif # PRODUCT_DEVICE
